export const OPEN_PROPERTY_MODAL = 'OPEN_PROPERTY_MODAL';
export const CLOSE_PROPERTY_MODAL = 'CLOSE_PROPERTY_MODAL';
export const CHANGE_PROPERTY_MODAL_COMPONENT = 'CHANGE_PROPERTY_MODAL_COMPONENT';
export const OPEN_PROPERTY_DEALS = 'OPEN_PROPERTY_DEALS';
export const OPEN_PROPERTY_INFO = 'OPEN_PROPERTY_INFO';
export const OPEN_PROPERTY_PHOTOS_GALLERY = 'OPEN_PROPERTY_PHOTOS_GALLERY';
export const OPEN_PROPERTY_REVIEWS = 'OPEN_PROPERTY_REVIEWS';
